language: rust

rust:
   - nightly-2019-01-16

install:
   - set -eo pipefail
   - pushd /tmp

   # Install DevkitARM
   - export DEVKITPRO="/opt/devkitpro"
   - export DEVKITARM="$DEVKITPRO/devkitARM"
   - export PATH="$PATH:$DEVKITARM/bin"
   - wget https://github.com/devkitPro/pacman/releases/download/v1.0.0/devkitpro-pacman.deb
   - sudo dpkg -i devkitpro-pacman.deb
   - sudo dkp-pacman -S --noconfirm devkitARM libctru

   # Install Xargo
   - cargo install xargo

   # Install Rust source
   - rustup component add rust-src
   - popd

script:
   - cd examples
   - export CC_3ds="arm-none-eabi-gcc"
   - export TARGET_CFLAGS="-mfloat-abi=hard -march=armv6k"
   - RUST_TARGET_PATH=$(pwd) xargo build --release
