[package]
name = "std"
version = "0.0.0"
authors = ["Ronald Kinard <furyhunter600@gmail.com>"]
license = "https://en.wikipedia.org/wiki/Zlib_License"

[lib]
crate-type = ["rlib"]

[dependencies]
alloc_system3ds = { path = "../alloc_system" }
ctru-sys = { path = "../ctru-sys" }
spin = "0.4"
