[package]
authors = ["Ronald Kinard <furyhunter600@gmail.com>"]
description = "A safe wrapper around smealum's ctrulib."
license = "https://en.wikipedia.org/wiki/Zlib_License"
name = "ctru-rs"
version = "0.7.1"

[lib]
crate-type = ["rlib"]
name = "ctru"

[dependencies.ctru-sys]
path = "../ctru-sys"
version = "0.4"

[dependencies.libc]
version = "0.2.43"

[dependencies.bitflags]
version = "1.0.0"

[dependencies.widestring]
version = "0.2.2"
